// Curated Sydney fishing spots database.
// Coordinates are real, targets and tips are based on commonly-known local knowledge.
// baseScore: spot reputation (0-100). Used as a starting point before condition scoring.
window.SYDNEY_SPOTS = [
  {
    id: "bare-island",
    name: "Bare Island, La Perouse",
    nameCn: "贝尔岛 · 拉佩鲁兹",
    lat: -33.9920, lng: 151.2340,
    type: "rock",
    baseScore: 92,
    species: ["Kingfish", "Bream", "Trevally", "Squid", "Drummer"],
    best: "Dawn & dusk. Run-in tide. Calm to light NE winds.",
    bestCn: "清晨与黄昏最佳；涨潮最佳；微东北风为宜。",
    techniques: ["Live yakkas for kingfish", "Berley + bread for bream", "Squid jigs along kelp edges"],
    tips: "Popular land-based game spot — kingfish in summer, drummer in winter. Slippery rocks: wear cleated boots and watch the swell.",
    tipsCn: "著名岸钓游钓点：夏季黄尾鰤，冬季黑毛。岩石湿滑，请穿防滑钉鞋并留意浪涌。",
    prefers: { calm: true, wind: ["NE", "N", "W", "SW"] }
  },
  {
    id: "clovelly",
    name: "Clovelly Rocks",
    nameCn: "克洛夫利岩石区",
    lat: -33.9145, lng: 151.2633,
    type: "rock",
    baseScore: 80,
    species: ["Luderick", "Bream", "Drummer", "Trevally"],
    best: "Incoming tide, morning. Green weed for luderick.",
    bestCn: "涨潮与早晨最佳，用绿苔钓黑鱼。",
    techniques: ["Float fishing with green weed", "Cunjevoi for drummer", "Light unweighted pilchard for bream"],
    tips: "Sheltered bay — good winter drummer and year-round luderick.",
    tipsCn: "海湾较避风，冬季黑毛、全年黑鱼均佳。",
    prefers: { calm: false, wind: ["W", "NW", "SW"] }
  },
  {
    id: "long-reef",
    name: "Long Reef Point",
    nameCn: "长礁角",
    lat: -33.7440, lng: 151.3125,
    type: "rock",
    baseScore: 85,
    species: ["Tailor", "Salmon", "Jewfish", "Kingfish"],
    best: "Dawn, dusk, run-out tide. Light westerlies.",
    bestCn: "清晨黄昏与退潮最佳，轻西风为宜。",
    techniques: ["Pilchards on gang hooks for tailor", "Metal slugs for salmon", "Live bait for jewfish after dark"],
    tips: "Walk out on low tide only. Exposed to southerly swell — do NOT fish in big seas.",
    tipsCn: "仅可在低潮步行前往；受南涌影响大，涌浪大时严禁下竿。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "bradleys-head",
    name: "Bradleys Head",
    nameCn: "布拉德利角",
    lat: -33.8475, lng: 151.2440,
    type: "harbour",
    baseScore: 82,
    species: ["Kingfish", "Bream", "Trevally", "Squid"],
    best: "Early morning. Run-in tide. Light winds.",
    bestCn: "清晨最佳，涨潮与微风最宜。",
    techniques: ["Live squid or yakkas for kingfish", "Berley for bream and trevally", "Squid jigs over weed"],
    tips: "Classic harbour kingfish spot. Deep water right off the rocks.",
    tipsCn: "经典港内钓黄尾点，岸边即深水区。",
    prefers: { calm: true, wind: ["N", "NW", "W", "SW"] }
  },
  {
    id: "the-spit",
    name: "The Spit Bridge",
    nameCn: "斯皮特大桥",
    lat: -33.8030, lng: 151.2480,
    type: "estuary",
    baseScore: 76,
    species: ["Flathead", "Bream", "Whiting", "Trevally"],
    best: "Run-out tide. Soft plastics along the drop-off.",
    bestCn: "退潮最佳，沿深沟抛软虫。",
    techniques: ["Soft plastics for flathead", "Prawn baits for bream", "Beach worms for whiting on sand flats"],
    tips: "Fishable in most weather. Watch for boat traffic.",
    tipsCn: "几乎任何天气都能钓；小心过往船只。",
    prefers: { calm: true, wind: ["N", "NW", "W", "SW", "S"] }
  },
  {
    id: "narrabeen-lake",
    name: "Narrabeen Lagoon",
    nameCn: "纳拉宾湖",
    lat: -33.7080, lng: 151.2870,
    type: "estuary",
    baseScore: 78,
    species: ["Flathead", "Whiting", "Bream", "Luderick"],
    best: "Last of the run-out tide at the entrance.",
    bestCn: "湖口退潮末最佳。",
    techniques: ["Surface poppers for whiting at dawn", "Soft plastics for flathead", "Live nippers for bream"],
    tips: "Family-friendly, shallow flats — great land-based lure spot.",
    tipsCn: "适合家庭；浅滩平坦，是非常好的岸钓拟饵点。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "silver-beach",
    name: "Silver Beach, Kurnell",
    nameCn: "银滩 · 库内尔",
    lat: -34.0140, lng: 151.2100,
    type: "beach",
    baseScore: 77,
    species: ["Whiting", "Flathead", "Bream", "Salmon"],
    best: "Run-in tide, early morning. Beach worms or nippers.",
    bestCn: "涨潮与清晨最佳，用海虫或钳虾。",
    techniques: ["Light running sinker rigs", "Beach worms for whiting", "Pilchards for salmon schools"],
    tips: "Sheltered from southerlies — fishable when ocean beaches are blown out.",
    tipsCn: "避南风，南风天海滩刮不下竿时此处仍可作钓。",
    prefers: { calm: true, wind: ["S", "SW", "SE"] }
  },
  {
    id: "balmoral",
    name: "Balmoral Beach",
    nameCn: "巴尔莫勒尔海滩",
    lat: -33.8260, lng: 151.2530,
    type: "harbour",
    baseScore: 74,
    species: ["Kingfish", "Bream", "Squid", "Whiting"],
    best: "Early/late. Live bait or squid jigs off the baths.",
    bestCn: "早晚最佳，泳池旁抛活饵或鱿鱼钩。",
    techniques: ["Squid jigs around moorings", "Unweighted prawns for bream"],
    tips: "Family spot with easy access. Kings chase bait schools in summer.",
    tipsCn: "家庭友好易达；夏季黄尾随饵群进湾。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "como",
    name: "Como, Georges River",
    nameCn: "柯摩 · 乔治河",
    lat: -33.9880, lng: 151.0640,
    type: "estuary",
    baseScore: 75,
    species: ["Flathead", "Bream", "Tailor", "Trevally"],
    best: "Run-out tide at dawn and dusk.",
    bestCn: "晨昏退潮最佳。",
    techniques: ["Soft plastics along drop-offs", "Live poddy mullet for big flathead"],
    tips: "Watch EPA fish-consumption advice for dioxin in some species upstream of Como.",
    tipsCn: "科摩以上河段有二噁英警示，请参照 EPA 食用建议。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "cronulla-point",
    name: "Cronulla Point",
    nameCn: "克罗努拉角",
    lat: -34.0580, lng: 151.1580,
    type: "rock",
    baseScore: 83,
    species: ["Drummer", "Bream", "Tailor", "Salmon", "Groper"],
    best: "Winter drummer on cunjevoi; summer pelagics at dawn.",
    bestCn: "冬季用海鞘钓黑毛，夏季清晨钓洄游鱼。",
    techniques: ["Cunjevoi float rigs", "Metal slugs for salmon", "Red crab for groper"],
    tips: "Exposed to southerly swell — check wave forecast before fishing.",
    tipsCn: "暴露南涌，下竿前务必查看浪高预报。",
    prefers: { calm: false, wind: ["W", "NW", "N"] }
  },
  {
    id: "manly-wharf",
    name: "Manly Wharf",
    nameCn: "曼利码头",
    lat: -33.8010, lng: 151.2850,
    type: "harbour",
    baseScore: 73,
    species: ["Squid", "Tailor", "Kingfish", "Yellowtail"],
    best: "Night fishing under lights for squid and tailor.",
    bestCn: "夜间码头灯下钓鱿鱼和竹荚鱼最佳。",
    techniques: ["Squid jigs", "Small metals for tailor schools"],
    tips: "Easy access, great for beginners. Avoid casting across ferry lanes.",
    tipsCn: "接近便利，适合新手；避免跨越渡轮航道抛竿。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "palm-beach",
    name: "Palm Beach Wharf, Pittwater",
    nameCn: "棕榈海滩码头 · 皮特沃特",
    lat: -33.5990, lng: 151.3240,
    type: "harbour",
    baseScore: 81,
    species: ["Kingfish", "Squid", "Bream", "Tailor"],
    best: "Dawn and dusk with live squid or yakkas.",
    bestCn: "晨昏用活鱿或小鲹最佳。",
    techniques: ["Live bait drift", "Squid jigs over weed beds"],
    tips: "Famous land-based kingfish haunt. Fights rods into pylons — use heavy leader.",
    tipsCn: "著名岸钓黄尾点；鱼易缠桩，使用粗碳线。",
    prefers: { calm: true, wind: ["N", "NW", "W", "SW"] }
  },
  {
    id: "clontarf",
    name: "Clontarf, Middle Harbour",
    nameCn: "克朗塔夫 · 中港",
    lat: -33.8060, lng: 151.2525,
    type: "estuary",
    baseScore: 72,
    species: ["Flathead", "Whiting", "Bream"],
    best: "High tide for whiting on sand flats.",
    bestCn: "高潮在沙滩平台钓沙梭最佳。",
    techniques: ["Surface poppers", "Nippers under a float"],
    tips: "Shallow, protected bay — ideal in bad weather.",
    tipsCn: "浅水避风湾，恶劣天气首选。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "parsley-bay",
    name: "Parsley Bay",
    nameCn: "帕斯利湾",
    lat: -33.8560, lng: 151.2730,
    type: "harbour",
    baseScore: 70,
    species: ["Squid", "Bream", "Trevally"],
    best: "Squid jigs in the evening over weed.",
    bestCn: "傍晚在海草床抛鱿鱼钩最佳。",
    techniques: ["Light spin, squid jigs"],
    tips: "Small, scenic bay. Beach swimming area — fish outside netted zone.",
    tipsCn: "小而美的海湾；注意避开游泳防鲨网区作钓。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "north-head",
    name: "North Head, Manly",
    nameCn: "北角 · 曼利",
    lat: -33.8200, lng: 151.2930,
    type: "rock",
    baseScore: 88,
    species: ["Kingfish", "Bonito", "Tailor", "Drummer"],
    best: "Dawn with live bait. Run-in tide.",
    bestCn: "清晨涨潮用活饵最佳。",
    techniques: ["Live squid/yakkas for kings", "Metal slugs at sunrise for bonito"],
    tips: "Serious land-based game platform. Heavy gear, cleats, and a buddy — never solo in swell.",
    tipsCn: "岸钓大物平台；重装备+钉鞋+同伴，严禁独自在涌浪中作钓。",
    prefers: { calm: true, wind: ["W", "NW", "N"] }
  },
  {
    id: "camp-cove",
    name: "Camp Cove / Watsons Bay",
    nameCn: "营地湾 · 华生湾",
    lat: -33.8400, lng: 151.2790,
    type: "harbour",
    baseScore: 76,
    species: ["Kingfish", "Trevally", "Squid", "Bream"],
    best: "Early morning incoming tide.",
    bestCn: "清晨涨潮最佳。",
    techniques: ["Live bait for kings", "Bread berley for bream"],
    tips: "Easy access near ferry wharf. Protected from southerlies.",
    tipsCn: "靠近渡轮码头，避南风。",
    prefers: { calm: true, wind: ["S", "SW", "SE"] }
  },
  {
    id: "malabar",
    name: "Malabar (Magic Point)",
    nameCn: "马拉巴 · 魔法角",
    lat: -33.9650, lng: 151.2500,
    type: "rock",
    baseScore: 84,
    species: ["Drummer", "Bream", "Groper", "Kingfish"],
    best: "Winter drummer; summer pelagics at change of light.",
    bestCn: "冬季黑毛；夏季晨昏洄游鱼最佳。",
    techniques: ["Cunjevoi for drummer", "Red crab for groper", "Live slimies for kings"],
    tips: "NOTE: EPA fishing ban on recreational harvest zones near Malabar — check current rules before keeping fish.",
    tipsCn: "注意：马拉巴附近有 EPA 禁捕区，食用前请查询最新规定。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "gunnamatta",
    name: "Gunnamatta Bay, Port Hacking",
    nameCn: "冈那玛塔湾 · 霍金港",
    lat: -34.0720, lng: 151.1480,
    type: "estuary",
    baseScore: 74,
    species: ["Flathead", "Whiting", "Bream", "Tailor"],
    best: "Run-out tide over sand flats.",
    bestCn: "退潮沙滩平台最佳。",
    techniques: ["Soft plastics", "Live nippers under float"],
    tips: "Protected bay, kid-friendly jetty.",
    tipsCn: "避风湾，码头适合家庭。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "brooklyn",
    name: "Brooklyn, Hawkesbury River",
    nameCn: "布鲁克林 · 霍克斯伯里河",
    lat: -33.5460, lng: 151.2300,
    type: "estuary",
    baseScore: 86,
    species: ["Jewfish", "Flathead", "Bream", "Tailor"],
    best: "Night session around tide change for jewfish.",
    bestCn: "夜钓换潮期钓石首鱼最佳。",
    techniques: ["Live mullet for jewfish", "Soft plastics on deep edges"],
    tips: "Famous for big jewfish. Bring heavy tackle and patience.",
    tipsCn: "以大石首鱼闻名；粗线大钩，耐心等候。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "cape-solander",
    name: "Cape Solander",
    nameCn: "索兰德角",
    lat: -34.0130, lng: 151.2270,
    type: "rock",
    baseScore: 87,
    species: ["Tailor", "Salmon", "Kingfish", "Bonito"],
    best: "Dawn with metals. Run-in tide.",
    bestCn: "清晨涨潮用铁板最佳。",
    techniques: ["Metal slugs", "Live bait for kings"],
    tips: "High rock platform — excellent whale watching in winter too.",
    tipsCn: "高岩平台；冬季也可观鲸。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  // ================== Northern Beaches ==================
  {
    id: "dee-why-point", name: "Dee Why Point", nameCn: "迪威角",
    lat: -33.7530, lng: 151.3020, type: "rock", baseScore: 78,
    species: ["Tailor", "Salmon", "Bream", "Drummer"],
    best: "Dawn/dusk, run-in tide.", bestCn: "晨昏涨潮最佳。",
    techniques: ["Metal slugs for pelagics", "Pilchards on gangs"],
    tips: "Accessible rock platform, watch for southerly swells.",
    tipsCn: "易达岩钓平台，注意南向涌浪。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "curl-curl", name: "South Curl Curl Rocks", nameCn: "南卷卷岩",
    lat: -33.7720, lng: 151.3000, type: "rock", baseScore: 75,
    species: ["Drummer", "Bream", "Groper", "Luderick"],
    best: "Winter incoming tide on cunjevoi.", bestCn: "冬季涨潮用海鞘最佳。",
    techniques: ["Float rigs", "Cunjevoi baits"],
    tips: "Good winter drummer spot, slippery when wet.",
    tipsCn: "冬季黑毛良点，湿滑注意。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "avalon-rocks", name: "Avalon Headland", nameCn: "阿瓦隆岬角",
    lat: -33.6340, lng: 151.3380, type: "rock", baseScore: 79,
    species: ["Kingfish", "Tailor", "Drummer", "Bream"],
    best: "Summer dawn for kings.", bestCn: "夏季清晨钓黄尾。",
    techniques: ["Live yakkas", "Metals"],
    tips: "Exposed platform on big days — check swell.",
    tipsCn: "暴露平台，大涌日严禁下竿。",
    prefers: { calm: false, wind: ["W", "SW"] }
  },
  {
    id: "whale-beach", name: "Whale Beach Headland", nameCn: "鲸鱼海滩岬",
    lat: -33.6100, lng: 151.3310, type: "rock", baseScore: 76,
    species: ["Tailor", "Salmon", "Bream", "Groper"],
    best: "Dawn with metals.", bestCn: "清晨用铁板最佳。",
    techniques: ["Metal slugs", "Gang-hook pilchards"],
    tips: "Beautiful northern platform, exposed to east swell.",
    tipsCn: "北岸秀丽岩台，受东涌影响。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "mona-vale-basin", name: "Mona Vale Rock Pool", nameCn: "莫纳谷岩池",
    lat: -33.6820, lng: 151.3120, type: "rock", baseScore: 70,
    species: ["Bream", "Luderick", "Drummer"],
    best: "High tide morning.", bestCn: "高潮清晨最佳。",
    techniques: ["Light float rig", "Unweighted prawns"],
    tips: "Family-friendly rocks near pool.",
    tipsCn: "岩池旁适合家庭。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "bungan-head", name: "Bungan Head", nameCn: "邦甘角",
    lat: -33.6580, lng: 151.3180, type: "rock", baseScore: 77,
    species: ["Drummer", "Bream", "Tailor", "Groper"],
    best: "Winter drummer on cabbage/cunje.", bestCn: "冬季黑毛最佳。",
    techniques: ["Float rig", "Heavy berley"],
    tips: "Quieter headland, good for escape from crowds.",
    tipsCn: "人少的岬角，避人流。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "turimetta", name: "Turimetta Head", nameCn: "图瑞梅塔角",
    lat: -33.6930, lng: 151.3050, type: "rock", baseScore: 74,
    species: ["Tailor", "Salmon", "Bream"],
    best: "Dawn/dusk run-in tide.", bestCn: "晨昏涨潮最佳。",
    techniques: ["Metals", "Pilchard gangs"],
    tips: "Walk in from Narrabeen Beach end.",
    tipsCn: "由纳拉宾海滩北端步入。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "narrabeen-beach", name: "North Narrabeen Beach", nameCn: "北纳拉宾海滩",
    lat: -33.7050, lng: 151.3020, type: "beach", baseScore: 76,
    species: ["Salmon", "Tailor", "Whiting", "Bream"],
    best: "Dawn gutters on run-in tide.", bestCn: "清晨涨潮冲沟钓最佳。",
    techniques: ["Pilchards on gangs", "Beach worms for whiting"],
    tips: "Read the gutters — deep holes next to sand bars.",
    tipsCn: "找冲沟深槽；沙坝旁的深窝是关键。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "collaroy", name: "Collaroy Beach", nameCn: "科拉罗伊海滩",
    lat: -33.7290, lng: 151.3020, type: "beach", baseScore: 72,
    species: ["Salmon", "Tailor", "Whiting"],
    best: "Dawn/dusk in gutters.", bestCn: "晨昏冲沟最佳。",
    techniques: ["Pilchards", "Beach worms"],
    tips: "Easy parking, fishable most tides.",
    tipsCn: "停车方便，多数潮位可钓。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "palm-beach-front", name: "Palm Beach (ocean side)", nameCn: "棕榈海滩 · 外海侧",
    lat: -33.5920, lng: 151.3280, type: "beach", baseScore: 78,
    species: ["Salmon", "Tailor", "Jewfish", "Whiting"],
    best: "Night tide change for jewfish.", bestCn: "夜间换潮钓石首鱼最佳。",
    techniques: ["Live squid for jewfish", "Beach worms for whiting"],
    tips: "Long beach with shifting gutters — walk and read.",
    tipsCn: "长沙滩冲沟变化大，多走多看。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  // ================== Eastern Beaches ==================
  {
    id: "bondi-rocks", name: "Ben Buckler (North Bondi)", nameCn: "本巴克勒 · 北邦迪",
    lat: -33.8880, lng: 151.2820, type: "rock", baseScore: 79,
    species: ["Kingfish", "Drummer", "Bream", "Tailor"],
    best: "Dawn, calm days.", bestCn: "清晨平静天最佳。",
    techniques: ["Live bait for kings", "Cunjevoi for drummer"],
    tips: "Famous eastern suburbs rock hop — wear cleats.",
    tipsCn: "东区著名岩钓点，请穿钉鞋。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "bronte-baths", name: "Bronte Baths Rocks", nameCn: "布朗特泳池岩",
    lat: -33.9035, lng: 151.2680, type: "rock", baseScore: 72,
    species: ["Bream", "Luderick", "Drummer"],
    best: "Incoming tide, early.", bestCn: "涨潮清晨最佳。",
    techniques: ["Light float", "Berley bread"],
    tips: "Easy access, gentler platform.",
    tipsCn: "易达平缓平台。",
    prefers: { calm: true, wind: ["W", "SW"] }
  },
  {
    id: "tamarama-rocks", name: "Tamarama Point", nameCn: "塔玛拉玛角",
    lat: -33.8995, lng: 151.2700, type: "rock", baseScore: 71,
    species: ["Bream", "Luderick", "Drummer"],
    best: "Run-in morning tide.", bestCn: "涨潮清晨最佳。",
    techniques: ["Light spin", "Float rig"],
    tips: "Small but productive when calm.",
    tipsCn: "小而精；平静日较佳。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "maroubra-rocks", name: "Mistral Point, Maroubra", nameCn: "米斯特拉尔角 · 马鲁巴",
    lat: -33.9500, lng: 151.2600, type: "rock", baseScore: 82,
    species: ["Kingfish", "Drummer", "Bream", "Tailor", "Groper"],
    best: "Dawn on calm days.", bestCn: "平静日清晨最佳。",
    techniques: ["Live bait", "Red crab for groper"],
    tips: "One of the best land-based king spots in the east.",
    tipsCn: "东区岸钓黄尾首选之一。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "little-bay", name: "Little Bay", nameCn: "小湾",
    lat: -33.9820, lng: 151.2510, type: "rock", baseScore: 75,
    species: ["Drummer", "Bream", "Luderick", "Tailor"],
    best: "Winter drummer; summer tailor at dusk.", bestCn: "冬黑毛，夏黄昏竹荚。",
    techniques: ["Cunjevoi", "Metal slugs"],
    tips: "Protected small bay, popular with locals.",
    tipsCn: "避风小湾，当地人爱去。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "coogee-rocks", name: "Dolphin Point, Coogee", nameCn: "海豚角 · 库吉",
    lat: -33.9190, lng: 151.2610, type: "rock", baseScore: 73,
    species: ["Bream", "Drummer", "Luderick"],
    best: "Incoming tide morning.", bestCn: "涨潮清晨最佳。",
    techniques: ["Float rig", "Berley"],
    tips: "Accessible rocks next to Coogee Beach.",
    tipsCn: "紧邻库吉海滩，方便易达。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "bondi-beach", name: "Bondi Beach (south corner)", nameCn: "邦迪海滩 · 南角",
    lat: -33.8940, lng: 151.2770, type: "beach", baseScore: 70,
    species: ["Salmon", "Tailor", "Whiting", "Bream"],
    best: "Dawn gutters.", bestCn: "清晨冲沟最佳。",
    techniques: ["Pilchards", "Beach worms"],
    tips: "Fishable outside swim zones early morning.",
    tipsCn: "清晨在非泳区作钓。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "maroubra-beach", name: "Maroubra Beach", nameCn: "马鲁巴海滩",
    lat: -33.9510, lng: 151.2570, type: "beach", baseScore: 74,
    species: ["Salmon", "Tailor", "Whiting", "Jewfish"],
    best: "Dawn/dusk gutters; night for jewfish.", bestCn: "晨昏冲沟；夜钓石首。",
    techniques: ["Gang hooks", "Beach worms", "Live squid"],
    tips: "Long beach with many productive holes.",
    tipsCn: "长滩深窝众多，多走多试。",
    prefers: { calm: true, wind: ["W"] }
  },
  // ================== Sydney Harbour ==================
  {
    id: "chowder-bay", name: "Chowder Bay", nameCn: "周德湾",
    lat: -33.8350, lng: 151.2520, type: "harbour", baseScore: 80,
    species: ["Kingfish", "Bream", "Squid", "Trevally"],
    best: "Early morning, run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Squid jigs", "Live bait drifts"],
    tips: "Deep water close to shore, historic jetty area.",
    tipsCn: "岸边即深水，历史码头区。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "taronga", name: "Taronga Zoo Wharf", nameCn: "塔隆加动物园码头",
    lat: -33.8430, lng: 151.2410, type: "harbour", baseScore: 72,
    species: ["Bream", "Squid", "Trevally"],
    best: "Evening squid jigging.", bestCn: "傍晚钓鱿鱼最佳。",
    techniques: ["Squid jigs", "Prawn baits"],
    tips: "Ferry wharf — avoid casting across lanes.",
    tipsCn: "渡轮码头，避开航道。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "nielsen-park", name: "Nielsen Park", nameCn: "尼尔森公园",
    lat: -33.8540, lng: 151.2680, type: "harbour", baseScore: 73,
    species: ["Squid", "Bream", "Trevally", "Whiting"],
    best: "Dawn run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Squid jigs", "Nippers under float"],
    tips: "Gentle shoreline, great family spot.",
    tipsCn: "平缓海岸，家庭友好。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "rose-bay", name: "Rose Bay Wharf", nameCn: "玫瑰湾码头",
    lat: -33.8720, lng: 151.2690, type: "harbour", baseScore: 71,
    species: ["Squid", "Bream", "Tailor"],
    best: "Night under lights for squid.", bestCn: "夜间灯下钓鱿。",
    techniques: ["Squid jigs", "Small metals"],
    tips: "Ferry wharf access, easy parking.",
    tipsCn: "渡轮码头，停车方便。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "rushcutters", name: "Rushcutters Bay", nameCn: "拉什卡特斯湾",
    lat: -33.8740, lng: 151.2300, type: "harbour", baseScore: 68,
    species: ["Bream", "Squid", "Flathead"],
    best: "Run-in tide early.", bestCn: "清晨涨潮最佳。",
    techniques: ["Unweighted prawns", "Squid jigs"],
    tips: "Sheltered inner harbour bay, CBD access.",
    tipsCn: "内港避风湾，近市中心。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "blues-point", name: "Blues Point", nameCn: "布鲁斯角",
    lat: -33.8490, lng: 151.2040, type: "harbour", baseScore: 74,
    species: ["Kingfish", "Squid", "Bream"],
    best: "Run-in tide with live bait.", bestCn: "涨潮用活饵最佳。",
    techniques: ["Live yakkas", "Squid jigs"],
    tips: "Iconic harbour spot right opposite Opera House.",
    tipsCn: "标志性点位，正对歌剧院。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "mosman-bay", name: "Mosman Bay Wharf", nameCn: "莫斯曼湾码头",
    lat: -33.8330, lng: 151.2310, type: "harbour", baseScore: 70,
    species: ["Bream", "Squid", "Trevally"],
    best: "Dawn or evening.", bestCn: "晨昏最佳。",
    techniques: ["Squid jigs", "Berley bream"],
    tips: "Quiet ferry wharf area.", tipsCn: "安静的渡轮区。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "cremorne-point", name: "Cremorne Point", nameCn: "克雷莫恩角",
    lat: -33.8420, lng: 151.2280, type: "harbour", baseScore: 75,
    species: ["Kingfish", "Bream", "Squid", "Trevally"],
    best: "Run-in tide early.", bestCn: "清晨涨潮最佳。",
    techniques: ["Live bait", "Squid jigs"],
    tips: "Deep water off point, kings patrol here.",
    tipsCn: "角尖即深水，黄尾巡游。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "middle-head", name: "Middle Head", nameCn: "中头",
    lat: -33.8270, lng: 151.2610, type: "harbour", baseScore: 83,
    species: ["Kingfish", "Bream", "Drummer", "Trevally"],
    best: "Dawn run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Live squid/yakkas", "Berley for bream"],
    tips: "Classic harbour mouth kingfish spot.",
    tipsCn: "经典港口岸钓黄尾点。",
    prefers: { calm: true, wind: ["W", "NW", "SW"] }
  },
  {
    id: "georges-heights", name: "Georges Heights", nameCn: "乔治高地",
    lat: -33.8320, lng: 151.2620, type: "harbour", baseScore: 77,
    species: ["Kingfish", "Squid", "Bream"],
    best: "Early morning.", bestCn: "清晨最佳。",
    techniques: ["Live bait", "Squid jigs"],
    tips: "Steep access but productive.",
    tipsCn: "下坡陡，但鱼情好。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "obelisk", name: "Obelisk Bay", nameCn: "方尖碑湾",
    lat: -33.8370, lng: 151.2590, type: "harbour", baseScore: 76,
    species: ["Squid", "Bream", "Flathead"],
    best: "Evening squid.", bestCn: "傍晚钓鱿。",
    techniques: ["Squid jigs over weed"],
    tips: "Clothing-optional beach — mind other users.",
    tipsCn: "该湾为天体海滩，请注意礼仪。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "farm-cove", name: "Farm Cove / Mrs Macquarie", nameCn: "农场湾 · 麦考瑞夫人座椅",
    lat: -33.8610, lng: 151.2220, type: "harbour", baseScore: 69,
    species: ["Bream", "Flathead", "Squid"],
    best: "Run-in tide, low light.", bestCn: "涨潮弱光最佳。",
    techniques: ["Prawns", "Small soft plastics"],
    tips: "Right next to Botanic Gardens — scenic session.",
    tipsCn: "紧邻植物园，风景绝佳。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "shark-island-side", name: "Shark Beach, Nielsen", nameCn: "鲨鱼海滩 · 尼尔森",
    lat: -33.8550, lng: 151.2670, type: "harbour", baseScore: 70,
    species: ["Whiting", "Bream", "Squid"],
    best: "High tide over sand.", bestCn: "高潮沙底最佳。",
    techniques: ["Nippers for whiting", "Squid jigs"],
    tips: "Shark net in summer; fish outside net.",
    tipsCn: "夏季有防鲨网，钓在网外。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "dawes-point", name: "Dawes Point / Hickson Rd", nameCn: "道斯角 · 希克森路",
    lat: -33.8560, lng: 151.2060, type: "harbour", baseScore: 71,
    species: ["Bream", "Kingfish", "Squid"],
    best: "Dawn run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Live bait", "Prawn baits"],
    tips: "Right under the Harbour Bridge.",
    tipsCn: "悉尼大桥正下方。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "woolloomooloo", name: "Woolloomooloo Wharf", nameCn: "伍鲁姆鲁码头",
    lat: -33.8700, lng: 151.2200, type: "harbour", baseScore: 66,
    species: ["Bream", "Squid", "Flathead"],
    best: "Night under lights.", bestCn: "夜间灯下最佳。",
    techniques: ["Squid jigs", "Prawn baits"],
    tips: "Walk-up city spot, steady bream.",
    tipsCn: "市区步行可达，黑鲷稳定。",
    prefers: { calm: true, wind: ["any"] }
  },
  // ================== Middle & Lane Cove ==================
  {
    id: "tunks-park", name: "Tunks Park", nameCn: "坦克斯公园",
    lat: -33.8170, lng: 151.2180, type: "estuary", baseScore: 68,
    species: ["Flathead", "Bream", "Whiting"],
    best: "Run-out tide.", bestCn: "退潮最佳。",
    techniques: ["Soft plastics", "Nippers"],
    tips: "Quiet creek mouth, family park.",
    tipsCn: "安静溪口，家庭公园。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "sailors-bay", name: "Sailors Bay, Castlecrag", nameCn: "水手湾 · 城堡崖",
    lat: -33.8060, lng: 151.2240, type: "estuary", baseScore: 73,
    species: ["Flathead", "Bream", "Whiting", "Luderick"],
    best: "Last of run-out tide.", bestCn: "退潮末段最佳。",
    techniques: ["Soft plastics", "Light float rigs"],
    tips: "Deep drop-offs close to shore.",
    tipsCn: "岸边即深沟。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "burns-bay", name: "Burns Bay, Lane Cove River", nameCn: "伯恩斯湾 · 莱恩湾河",
    lat: -33.8230, lng: 151.1600, type: "estuary", baseScore: 70,
    species: ["Flathead", "Bream", "Jewfish"],
    best: "Tide change at dawn/dusk.", bestCn: "晨昏换潮最佳。",
    techniques: ["Live mullet", "Deep soft plastics"],
    tips: "Lane Cove River holds surprise jewfish.",
    tipsCn: "河段有意外石首鱼。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "longueville", name: "Longueville Wharf", nameCn: "朗格维尔码头",
    lat: -33.8280, lng: 151.1700, type: "estuary", baseScore: 67,
    species: ["Bream", "Flathead", "Squid"],
    best: "Run-in tide.", bestCn: "涨潮最佳。",
    techniques: ["Prawns", "Squid jigs"],
    tips: "Small wharf, easy access.", tipsCn: "小码头，易达。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "kissing-point", name: "Kissing Point, Putney", nameCn: "吻角 · 普特尼",
    lat: -33.8330, lng: 151.1090, type: "estuary", baseScore: 69,
    species: ["Flathead", "Bream", "Jewfish"],
    best: "Run-out tide.", bestCn: "退潮最佳。",
    techniques: ["Soft plastics", "Live bait"],
    tips: "Parramatta River — jewfish on live bait at night.",
    tipsCn: "帕拉玛塔河；夜钓活饵有石首鱼。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "cabarita", name: "Cabarita Wharf", nameCn: "卡巴里塔码头",
    lat: -33.8490, lng: 151.1120, type: "estuary", baseScore: 65,
    species: ["Bream", "Flathead"],
    best: "Run-in tide morning.", bestCn: "清晨涨潮最佳。",
    techniques: ["Prawn baits", "Plastics"],
    tips: "Follow EPA advisory for Parramatta River fish consumption.",
    tipsCn: "请遵循 EPA 帕拉玛塔河食用建议。",
    prefers: { calm: true, wind: ["any"] }
  },
  // ================== Southern / Botany / Cronulla ==================
  {
    id: "yarra-bay", name: "Yarra Bay", nameCn: "雅拉湾",
    lat: -33.9810, lng: 151.2310, type: "harbour", baseScore: 71,
    species: ["Whiting", "Flathead", "Bream"],
    best: "High tide over flats.", bestCn: "高潮沙滩最佳。",
    techniques: ["Nippers", "Soft plastics"],
    tips: "Sheltered Botany Bay side.",
    tipsCn: "植物湾避风一侧。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "foreshores-botany", name: "Botany Bay Foreshores", nameCn: "植物湾海岸公园",
    lat: -33.9980, lng: 151.1950, type: "estuary", baseScore: 68,
    species: ["Flathead", "Whiting", "Bream", "Tailor"],
    best: "Dawn/dusk.", bestCn: "晨昏最佳。",
    techniques: ["Beach worms", "Soft plastics"],
    tips: "Long shoreline, many access points.",
    tipsCn: "海岸线长，入口多。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "sans-souci", name: "Sans Souci Wharf", nameCn: "桑苏西码头",
    lat: -33.9900, lng: 151.1340, type: "estuary", baseScore: 72,
    species: ["Bream", "Flathead", "Tailor", "Whiting"],
    best: "Run-in tide.", bestCn: "涨潮最佳。",
    techniques: ["Prawns", "Squid strips"],
    tips: "Georges River mouth wharf, reliable bream.",
    tipsCn: "乔治河口码头，黑鲷稳定。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "dolls-point", name: "Dolls Point", nameCn: "洋娃娃角",
    lat: -33.9930, lng: 151.1490, type: "beach", baseScore: 67,
    species: ["Whiting", "Flathead"],
    best: "High tide sand flats.", bestCn: "高潮沙滩最佳。",
    techniques: ["Beach worms", "Nippers"],
    tips: "Family flats inside Botany Bay.",
    tipsCn: "植物湾内家庭沙滩。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "cooks-river", name: "Cooks River Mouth", nameCn: "库克河口",
    lat: -33.9520, lng: 151.1660, type: "estuary", baseScore: 66,
    species: ["Flathead", "Bream"],
    best: "Run-out tide.", bestCn: "退潮最佳。",
    techniques: ["Soft plastics"],
    tips: "Catch & release preferred due to historic contamination.",
    tipsCn: "历史污染，建议钓后放流。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "taren-point", name: "Taren Point", nameCn: "塔伦角",
    lat: -34.0200, lng: 151.1200, type: "estuary", baseScore: 74,
    species: ["Flathead", "Bream", "Whiting"],
    best: "Run-out tide on sand flats.", bestCn: "退潮沙滩最佳。",
    techniques: ["Surface poppers", "Soft plastics"],
    tips: "Georges River flats — surface whiting in summer.",
    tipsCn: "乔治河沙滩，夏季水面钓沙梭。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "bundeena", name: "Bundeena Wharf", nameCn: "邦德纳码头",
    lat: -34.0820, lng: 151.1510, type: "estuary", baseScore: 76,
    species: ["Flathead", "Bream", "Whiting", "Tailor"],
    best: "Run-out tide from Port Hacking.", bestCn: "霍金港退潮最佳。",
    techniques: ["Soft plastics", "Nippers"],
    tips: "Gateway to Royal NP — scenic session.",
    tipsCn: "皇家国家公园门口，风景秀丽。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "wanda-beach", name: "Wanda Beach", nameCn: "万达海滩",
    lat: -34.0430, lng: 151.1720, type: "beach", baseScore: 75,
    species: ["Salmon", "Tailor", "Whiting", "Jewfish"],
    best: "Dawn gutters, night jewfish.", bestCn: "晨冲沟、夜石首。",
    techniques: ["Pilchards", "Live squid"],
    tips: "Long beach, drive north from Cronulla.",
    tipsCn: "长滩，从克罗努拉北行可达。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "greenhills", name: "Greenhills Beach", nameCn: "绿山海滩",
    lat: -34.0320, lng: 151.1810, type: "beach", baseScore: 72,
    species: ["Salmon", "Tailor", "Whiting"],
    best: "Dawn/dusk gutters.", bestCn: "晨昏冲沟最佳。",
    techniques: ["Metals", "Beach worms"],
    tips: "Less crowded than Wanda.",
    tipsCn: "人比万达少。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "burraneer", name: "Burraneer Bay", nameCn: "布拉尼尔湾",
    lat: -34.0510, lng: 151.1370, type: "estuary", baseScore: 72,
    species: ["Flathead", "Bream", "Whiting"],
    best: "Run-in tide morning.", bestCn: "清晨涨潮最佳。",
    techniques: ["Soft plastics", "Live nippers"],
    tips: "Protected bay in Port Hacking.",
    tipsCn: "霍金港内避风湾。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "yowie-bay", name: "Yowie Bay", nameCn: "尤维湾",
    lat: -34.0540, lng: 151.1220, type: "estuary", baseScore: 70,
    species: ["Flathead", "Bream"],
    best: "Run-out tide.", bestCn: "退潮最佳。",
    techniques: ["Plastics", "Prawn baits"],
    tips: "Quiet Port Hacking arm, boat-friendly.",
    tipsCn: "霍金港安静支湾，适合小船。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "gymea-bay", name: "Gymea Bay", nameCn: "吉米亚湾",
    lat: -34.0420, lng: 151.0900, type: "estuary", baseScore: 68,
    species: ["Flathead", "Bream", "Whiting"],
    best: "Morning run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Nippers", "Soft plastics"],
    tips: "Inner Port Hacking, very sheltered.",
    tipsCn: "霍金港深处，极避风。",
    prefers: { calm: true, wind: ["any"] }
  },
  // ================== Hawkesbury / Pittwater ==================
  {
    id: "patonga", name: "Patonga Beach", nameCn: "帕通加海滩",
    lat: -33.5470, lng: 151.2720, type: "estuary", baseScore: 76,
    species: ["Flathead", "Bream", "Jewfish", "Tailor"],
    best: "Tide change at dawn.", bestCn: "清晨换潮最佳。",
    techniques: ["Live prawns", "Soft plastics"],
    tips: "Hawkesbury entrance — big flatties and jewfish.",
    tipsCn: "霍克斯伯里入口，大扁头与石首。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "bobbin-head", name: "Bobbin Head", nameCn: "波宾头",
    lat: -33.6570, lng: 151.1550, type: "estuary", baseScore: 73,
    species: ["Flathead", "Bream", "Jewfish"],
    best: "Run-out tide in deep channels.", bestCn: "深沟退潮最佳。",
    techniques: ["Live bait", "Soft plastics"],
    tips: "Ku-ring-gai Chase NP — pay park fee.",
    tipsCn: "库灵盖国家公园，需停车费。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "berowra-waters", name: "Berowra Waters", nameCn: "贝罗拉水域",
    lat: -33.6220, lng: 151.1450, type: "estuary", baseScore: 74,
    species: ["Flathead", "Bream", "Jewfish", "Tailor"],
    best: "Run-out tide.", bestCn: "退潮最佳。",
    techniques: ["Vibes", "Live mullet"],
    tips: "Deep river bends hold big jewfish.",
    tipsCn: "深弯有大石首鱼。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "flint-steel", name: "Flint & Steel Beach", nameCn: "火石与钢海滩",
    lat: -33.5620, lng: 151.2440, type: "estuary", baseScore: 75,
    species: ["Jewfish", "Flathead", "Bream"],
    best: "Night tide change.", bestCn: "夜间换潮最佳。",
    techniques: ["Live mullet", "Squid baits"],
    tips: "Boat access only — classic Hawkesbury jewfish hole.",
    tipsCn: "仅船可达，经典霍克斯伯里石首窝。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "church-point", name: "Church Point, Pittwater", nameCn: "教堂角 · 皮特沃特",
    lat: -33.6520, lng: 151.2830, type: "harbour", baseScore: 72,
    species: ["Squid", "Bream", "Flathead"],
    best: "Evening squid over weed.", bestCn: "傍晚海草床钓鱿最佳。",
    techniques: ["Squid jigs", "Plastics"],
    tips: "Ferry wharf — steady squid.",
    tipsCn: "渡轮码头，鱿鱼稳定。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "clareville", name: "Clareville Beach", nameCn: "克莱尔维尔海滩",
    lat: -33.6280, lng: 151.3090, type: "harbour", baseScore: 70,
    species: ["Whiting", "Flathead", "Bream"],
    best: "High tide sand flats.", bestCn: "高潮沙滩最佳。",
    techniques: ["Nippers", "Beach worms"],
    tips: "Pittwater sheltered beach, family-friendly.",
    tipsCn: "皮特沃特避风海滩，家庭友好。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "bayview", name: "Bayview Baths, Pittwater", nameCn: "海景泳池 · 皮特沃特",
    lat: -33.6600, lng: 151.3020, type: "harbour", baseScore: 69,
    species: ["Squid", "Bream"],
    best: "Evening squid.", bestCn: "傍晚钓鱿最佳。",
    techniques: ["Squid jigs"],
    tips: "Small jetty with seagrass beds.",
    tipsCn: "小码头，周边海草床。",
    prefers: { calm: true, wind: ["any"] }
  },

  // ================== East Coast · 热门高分岩钓平台 ==================
  {
    id: "hornby-light", name: "Hornby Lighthouse, South Head", nameCn: "霍恩比灯塔 · 南角",
    lat: -33.8330, lng: 151.2820, type: "rock", baseScore: 94,
    species: ["Kingfish", "Tailor", "Bonito", "Trevally", "Drummer"],
    best: "Dawn run-in tide. Live squid or yakkas.",
    bestCn: "清晨涨潮，用活鱿/小鲹最佳。",
    techniques: ["Live bait on balloon/float", "Metal slugs at sunrise", "Ganged pilchards for tailor"],
    tips: "Legendary land-based king platform. Deep water straight off the rocks. NEVER fish solo or in swell over 2m.",
    tipsCn: "传奇岸钓黄尾平台，岸边直接深水。涌浪 >2m 严禁，切勿单人作钓。",
    prefers: { calm: true, wind: ["W", "NW", "SW"] }
  },
  {
    id: "the-gap-safe", name: "Dunbar Head (南角安全段)", nameCn: "邓巴角",
    lat: -33.8470, lng: 151.2830, type: "rock", baseScore: 82,
    species: ["Drummer", "Bream", "Groper", "Luderick"],
    best: "Winter drummer on cunjevoi.", bestCn: "冬季海鞘钓黑毛最佳。",
    techniques: ["Float rig", "Heavy cunjevoi bait"],
    tips: "Stay well back from the cliff edge. Fish only the lower safe ledges.",
    tipsCn: "远离悬崖边，仅在低位安全台作钓。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "macquarie-light", name: "Macquarie Lighthouse", nameCn: "麦考瑞灯塔",
    lat: -33.8520, lng: 151.2830, type: "rock", baseScore: 83,
    species: ["Kingfish", "Tailor", "Drummer", "Bonito"],
    best: "Dawn; run-in tide; calm seas.", bestCn: "平静日清晨涨潮。",
    techniques: ["Live bait", "Metal slugs"],
    tips: "High platform; only access in calm conditions.",
    tipsCn: "高岩台，仅平静海况下前往。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "diamond-bay", name: "Diamond Bay Rocks", nameCn: "钻石湾岩台",
    lat: -33.8680, lng: 151.2820, type: "rock", baseScore: 85,
    species: ["Kingfish", "Drummer", "Groper", "Bream"],
    best: "Dawn live bait. Calm only.", bestCn: "清晨活饵，仅平静日。",
    techniques: ["Live yakkas/slimies", "Red crab for groper"],
    tips: "Vaucluse cliff spot. Very popular with locals — take cleats and rope.",
    tipsCn: "沃克鲁斯悬崖点，本地热门；钉鞋+绳索必备。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "dover-heights", name: "Dover Heights Cliffs", nameCn: "多佛高地岩礁",
    lat: -33.8790, lng: 151.2810, type: "rock", baseScore: 80,
    species: ["Drummer", "Bream", "Kingfish", "Groper"],
    best: "Winter drummer.", bestCn: "冬季黑毛最佳。",
    techniques: ["Cunjevoi", "Heavy float rig"],
    tips: "Access via Rodney Reserve. Long walk in.",
    tipsCn: "由罗德尼保留地步入，路程较远。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "mackenzies-point", name: "Mackenzies Point, Bondi", nameCn: "麦肯齐角 · 邦迪",
    lat: -33.8970, lng: 151.2760, type: "rock", baseScore: 81,
    species: ["Kingfish", "Bream", "Drummer", "Tailor"],
    best: "Dawn on the run-in.", bestCn: "清晨涨潮最佳。",
    techniques: ["Live bait", "Pilchards"],
    tips: "Between Bondi & Tamarama — great kings on calm summer mornings.",
    tipsCn: "邦迪—塔玛拉玛间；夏季平静清晨多黄尾。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "gordons-bay", name: "Gordons Bay", nameCn: "戈登湾",
    lat: -33.9110, lng: 151.2640, type: "rock", baseScore: 76,
    species: ["Bream", "Luderick", "Drummer", "Trevally"],
    best: "Incoming tide morning.", bestCn: "清晨涨潮最佳。",
    techniques: ["Float rig with weed", "Berley bread"],
    tips: "Protected bay between Clovelly & Coogee — very steady bream.",
    tipsCn: "克洛夫利与库吉间避风湾，黑鲷非常稳定。",
    prefers: { calm: true, wind: ["W", "SW"] }
  },
  {
    id: "shark-point-clovelly", name: "Shark Point, Clovelly", nameCn: "鲨角 · 克洛夫利",
    lat: -33.9160, lng: 151.2680, type: "rock", baseScore: 84,
    species: ["Kingfish", "Drummer", "Bream", "Groper"],
    best: "Dawn live bait; winter drummer.", bestCn: "清晨活饵；冬钓黑毛。",
    techniques: ["Live yakkas", "Cunjevoi for drummer", "Red crab for groper"],
    tips: "One of the most reliable east-coast land-based king spots.",
    tipsCn: "东海岸最稳定岸钓黄尾点之一。",
    prefers: { calm: true, wind: ["W", "NW", "SW"] }
  },
  {
    id: "lurline-bay", name: "Lurline Bay", nameCn: "卢尔琳湾",
    lat: -33.9350, lng: 151.2620, type: "rock", baseScore: 75,
    species: ["Bream", "Drummer", "Luderick"],
    best: "Morning run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Float rig", "Light bream setups"],
    tips: "Small protected bay, reliable winter session.",
    tipsCn: "小而避风，冬季稳定。",
    prefers: { calm: true, wind: ["W", "SW"] }
  },
  {
    id: "jew-hole", name: "Maroubra Jew Hole", nameCn: "马鲁巴石首鱼窝",
    lat: -33.9530, lng: 151.2610, type: "rock", baseScore: 86,
    species: ["Jewfish", "Drummer", "Bream", "Kingfish"],
    best: "Night tide change for jewfish.", bestCn: "夜间换潮钓石首鱼最佳。",
    techniques: ["Live squid/mullet", "Heavy running sinker rigs"],
    tips: "Legendary deep ledge at Maroubra. Heavy tackle and a headlamp.",
    tipsCn: "马鲁巴著名深岩台，粗线重钩+头灯。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "magic-point", name: "Magic Point, Maroubra", nameCn: "魔法角 · 马鲁巴",
    lat: -33.9570, lng: 151.2620, type: "rock", baseScore: 85,
    species: ["Kingfish", "Bonito", "Tailor", "Drummer"],
    best: "Dawn pelagics in summer.", bestCn: "夏季清晨钓洄游鱼。",
    techniques: ["Metal slugs", "Live bait"],
    tips: "Iconic headland with grey nurse sharks below — catch & release encouraged.",
    tipsCn: "标志性岬角，水下有灰护士鲨，鼓励放流。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "boora-point", name: "Boora Point, Malabar", nameCn: "布拉角 · 马拉巴",
    lat: -33.9720, lng: 151.2540, type: "rock", baseScore: 82,
    species: ["Drummer", "Bream", "Groper", "Tailor"],
    best: "Winter drummer high tide.", bestCn: "冬季高潮钓黑毛。",
    techniques: ["Cunjevoi", "Bread for bream"],
    tips: "Walk-in platform, south of Malabar headland.",
    tipsCn: "马拉巴岬角南侧步入平台。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "cape-banks", name: "Cape Banks, La Perouse", nameCn: "班克斯角 · 拉佩鲁兹",
    lat: -34.0000, lng: 151.2450, type: "rock", baseScore: 88,
    species: ["Kingfish", "Drummer", "Bonito", "Groper", "Tailor"],
    best: "Dawn live bait, run-in tide.", bestCn: "清晨活饵涨潮最佳。",
    techniques: ["Live yakkas/squid", "Metal slugs", "Red crab"],
    tips: "Walk across the land bridge at low tide. Long walk but worth it.",
    tipsCn: "低潮通过陆桥进入，路程长但值得。",
    prefers: { calm: true, wind: ["W", "NW", "SW"] }
  },
  {
    id: "henry-head", name: "Henry Head", nameCn: "亨利角",
    lat: -33.9990, lng: 151.2410, type: "rock", baseScore: 86,
    species: ["Kingfish", "Bonito", "Tailor", "Drummer", "Salmon"],
    best: "Dawn run-in tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Metal slugs", "Live bait"],
    tips: "Famous for summer bonito blitzes on metals at sunrise.",
    tipsCn: "夏季清晨炮鱼群冲饵著名。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "congwong", name: "Congwong Beach", nameCn: "孔旺海滩",
    lat: -33.9940, lng: 151.2310, type: "beach", baseScore: 72,
    species: ["Whiting", "Flathead", "Bream"],
    best: "High tide flats.", bestCn: "高潮沙滩最佳。",
    techniques: ["Nippers", "Beach worms"],
    tips: "Sheltered Botany Bay beach, family spot.",
    tipsCn: "植物湾内避风海滩，家庭友好。",
    prefers: { calm: true, wind: ["any"] }
  },
  {
    id: "frenchmans-bay", name: "Frenchmans Bay", nameCn: "法国人湾",
    lat: -33.9880, lng: 151.2330, type: "harbour", baseScore: 74,
    species: ["Bream", "Whiting", "Squid", "Flathead"],
    best: "Run-in tide morning.", bestCn: "清晨涨潮最佳。",
    techniques: ["Squid jigs", "Prawn baits"],
    tips: "Protected beach, good squid over weed beds.",
    tipsCn: "避风海滩，海草床鱿鱼良好。",
    prefers: { calm: true, wind: ["any"] }
  },

  // ================== Kurnell Peninsula · 顶级 land-based ==================
  {
    id: "inscription-point", name: "Inscription Point, Kurnell", nameCn: "铭文角 · 库内尔",
    lat: -34.0050, lng: 151.2270, type: "rock", baseScore: 88,
    species: ["Kingfish", "Bonito", "Tailor", "Drummer", "Salmon"],
    best: "Dawn live bait on run-in tide.", bestCn: "清晨涨潮活饵最佳。",
    techniques: ["Live yakkas", "Metal slugs", "Ganged pilchards"],
    tips: "Near Cook's landing place. Short walk, deep water close in.",
    tipsCn: "库克登陆地附近，步程短岸边即深水。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "cape-baily", name: "Cape Baily", nameCn: "贝利角",
    lat: -34.0380, lng: 151.2290, type: "rock", baseScore: 85,
    species: ["Tailor", "Salmon", "Drummer", "Kingfish"],
    best: "Dawn metals.", bestCn: "清晨铁板最佳。",
    techniques: ["Metal slugs", "Gang-hook pilchards"],
    tips: "Walk from Cape Solander car park along coastal track.",
    tipsCn: "从索兰德角停车场沿海岸步道前往。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "tabbagai", name: "Tabbagai Gap", nameCn: "塔巴盖峡",
    lat: -34.0460, lng: 151.2250, type: "rock", baseScore: 80,
    species: ["Drummer", "Bream", "Groper"],
    best: "Winter high tide with cunjevoi.", bestCn: "冬季高潮海鞘钓。",
    techniques: ["Float rig", "Red crab"],
    tips: "Kurnell back-beach ledge, exposed — check swell.",
    tipsCn: "库内尔后滩岩台，暴露，查涌浪。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "potter-point", name: "Potter Point", nameCn: "波特角",
    lat: -34.0550, lng: 151.2030, type: "rock", baseScore: 84,
    species: ["Tailor", "Salmon", "Kingfish", "Bonito", "Drummer"],
    best: "Dawn metals; run-in tide.", bestCn: "清晨铁板涨潮最佳。",
    techniques: ["Metal slugs", "Live bait"],
    tips: "South Kurnell — classic pelagic platform, follow the coastal trail.",
    tipsCn: "南库内尔经典洄游鱼岩台，沿海岸小径前往。",
    prefers: { calm: false, wind: ["W", "NW"] }
  },
  {
    id: "boat-harbour-kurnell", name: "Boat Harbour, Kurnell", nameCn: "船湾 · 库内尔",
    lat: -34.0620, lng: 151.1960, type: "rock", baseScore: 83,
    species: ["Kingfish", "Tailor", "Drummer", "Salmon"],
    best: "Dawn with live bait.", bestCn: "清晨活饵最佳。",
    techniques: ["Live yakkas", "Metals"],
    tips: "Short 4WD access. Protected landing area.",
    tipsCn: "需越野车进入，登船平台避风。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "voodoo-point", name: "Voodoo Point, Cronulla", nameCn: "伏都角 · 克罗努拉",
    lat: -34.0700, lng: 151.1700, type: "rock", baseScore: 82,
    species: ["Drummer", "Bream", "Tailor", "Groper"],
    best: "Winter high tide.", bestCn: "冬季高潮最佳。",
    techniques: ["Cunjevoi", "Float rigs"],
    tips: "Short walk from Bass & Flinders Point.",
    tipsCn: "由巴斯与弗林德斯角步入较近。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "bass-flinders", name: "Bass & Flinders Point", nameCn: "巴斯与弗林德斯角",
    lat: -34.0720, lng: 151.1730, type: "rock", baseScore: 81,
    species: ["Kingfish", "Tailor", "Salmon", "Drummer"],
    best: "Dawn on incoming tide.", bestCn: "清晨涨潮最佳。",
    techniques: ["Live bait", "Metal slugs"],
    tips: "Cronulla south point, easy parking at lookout.",
    tipsCn: "克罗努拉南角，观景台停车方便。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "shelly-headland", name: "Shelly Headland, Cronulla", nameCn: "谢利岬 · 克罗努拉",
    lat: -34.0680, lng: 151.1620, type: "rock", baseScore: 78,
    species: ["Drummer", "Bream", "Luderick"],
    best: "Winter drummer on cunje.", bestCn: "冬季黑毛最佳。",
    techniques: ["Float rig", "Cunjevoi baits"],
    tips: "Easy walk-in from Cronulla Esplanade.",
    tipsCn: "由克罗努拉海滨路步行可达。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "jibbon-head", name: "Jibbon Head, Bundeena", nameCn: "吉本角 · 邦德纳",
    lat: -34.0820, lng: 151.1680, type: "rock", baseScore: 83,
    species: ["Drummer", "Kingfish", "Tailor", "Groper"],
    best: "Dawn and winter high tide.", bestCn: "清晨与冬季高潮最佳。",
    techniques: ["Live bait", "Cunjevoi"],
    tips: "Enter via Bundeena, walk the Jibbon loop. Royal NP park pass.",
    tipsCn: "由邦德纳进入，需皇家国家公园通行证。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },

  // ================== Northern Beaches 补充 ==================
  {
    id: "barrenjoey", name: "Barrenjoey Headland", nameCn: "巴伦乔伊岬",
    lat: -33.5800, lng: 151.3340, type: "rock", baseScore: 86,
    species: ["Kingfish", "Tailor", "Bonito", "Drummer", "Salmon"],
    best: "Dawn run-in tide, calm seas.", bestCn: "平静日清晨涨潮最佳。",
    techniques: ["Live squid/yakkas", "Metal slugs"],
    tips: "Most northern Sydney headland. Long walk to lighthouse platforms.",
    tipsCn: "悉尼最北岬角，到灯塔平台路程较长。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "north-avalon", name: "North Avalon Headland", nameCn: "北阿瓦隆岬角",
    lat: -33.6250, lng: 151.3380, type: "rock", baseScore: 80,
    species: ["Kingfish", "Drummer", "Tailor", "Bream"],
    best: "Dawn with live bait.", bestCn: "清晨活饵最佳。",
    techniques: ["Live yakkas", "Metal slugs"],
    tips: "Summer kings chase bait along the wash.",
    tipsCn: "夏季黄尾沿浪花追饵。",
    prefers: { calm: true, wind: ["W", "NW"] }
  },
  {
    id: "bilgola-head", name: "Bilgola Head", nameCn: "比尔戈拉岬",
    lat: -33.6430, lng: 151.3290, type: "rock", baseScore: 76,
    species: ["Drummer", "Bream", "Groper", "Luderick"],
    best: "Winter drummer.", bestCn: "冬季黑毛最佳。",
    techniques: ["Cunjevoi", "Float rig"],
    tips: "Access from Bilgola Beach north end.",
    tipsCn: "由比尔戈拉海滩北端进入。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "newport-reef", name: "Newport Reef", nameCn: "纽波特礁",
    lat: -33.6580, lng: 151.3260, type: "rock", baseScore: 78,
    species: ["Tailor", "Salmon", "Drummer", "Bream"],
    best: "Dawn with metals.", bestCn: "清晨用铁板最佳。",
    techniques: ["Metals", "Pilchards"],
    tips: "Access via Newport Beach south end at low tide.",
    tipsCn: "低潮由纽波特海滩南端进入。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "warriewood-head", name: "Warriewood Headland", nameCn: "瓦里伍德岬",
    lat: -33.6900, lng: 151.3080, type: "rock", baseScore: 74,
    species: ["Drummer", "Bream", "Tailor"],
    best: "Winter high tide.", bestCn: "冬季高潮最佳。",
    techniques: ["Cunjevoi", "Float rig"],
    tips: "Walk-in from Warriewood Beach.",
    tipsCn: "由瓦里伍德海滩步入。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "queenscliff-bombora", name: "Queenscliff Bombora", nameCn: "昆斯克利夫暗礁",
    lat: -33.7780, lng: 151.2930, type: "rock", baseScore: 79,
    species: ["Tailor", "Salmon", "Kingfish", "Drummer"],
    best: "Dawn on calm days.", bestCn: "平静日清晨最佳。",
    techniques: ["Metal slugs", "Live bait"],
    tips: "Between Freshwater & Queenscliff. Watch sets — washy spot.",
    tipsCn: "淡水湾与昆斯克利夫间，浪涌明显。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "freshwater-head", name: "Freshwater Headland", nameCn: "淡水湾岬",
    lat: -33.7820, lng: 151.2940, type: "rock", baseScore: 77,
    species: ["Drummer", "Bream", "Tailor", "Luderick"],
    best: "Winter drummer on the high tide.", bestCn: "冬季高潮钓黑毛。",
    techniques: ["Cunjevoi", "Light float rig"],
    tips: "Easy access from pool end of Freshwater Beach.",
    tipsCn: "从淡水湾泳池端易达。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "north-curl-curl", name: "North Curl Curl Headland", nameCn: "北卷卷岬",
    lat: -33.7690, lng: 151.3030, type: "rock", baseScore: 78,
    species: ["Drummer", "Bream", "Tailor", "Groper"],
    best: "Winter cunjevoi session.", bestCn: "冬季海鞘作钓。",
    techniques: ["Float rig with cunje", "Red crab"],
    tips: "Good mix of drummer and groper in winter.",
    tipsCn: "冬季黑毛与隆头鱼兼得。",
    prefers: { calm: false, wind: ["W"] }
  },
  {
    id: "long-reef-west", name: "Long Reef Aquatic Reserve (west)", nameCn: "长礁水生保护区 · 西侧",
    lat: -33.7470, lng: 151.3100, type: "rock", baseScore: 80,
    species: ["Drummer", "Bream", "Luderick", "Trevally"],
    best: "Run-in tide morning.", bestCn: "清晨涨潮最佳。",
    techniques: ["Float rigs", "Berley"],
    tips: "NOTE: Parts are no-take aquatic reserve. Check current zoning before keeping fish.",
    tipsCn: "部分为禁捕区，请查询最新分区规定。",
    prefers: { calm: true, wind: ["W"] }
  },
  {
    id: "dee-why-headland", name: "Dee Why Headland", nameCn: "迪威岬",
    lat: -33.7560, lng: 151.3030, type: "rock", baseScore: 75,
    species: ["Drummer", "Bream", "Tailor"],
    best: "Winter high tide.", bestCn: "冬季高潮最佳。",
    techniques: ["Cunjevoi", "Pilchards"],
    tips: "Walk from Dee Why Point south.",
    tipsCn: "由迪威角南行步入。",
    prefers: { calm: false, wind: ["W"] }
  }
];
